# Generated by Django 4.2.4 on 2024-12-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Em_Id', models.CharField(max_length=10)),
                ('Em_Name', models.CharField(max_length=40)),
                ('Em_Mobile', models.CharField(max_length=14)),
                ('Em_Salary', models.CharField(max_length=10)),
                ('Em_Email', models.EmailField(max_length=40)),
                ('Em_Birth_Date', models.DateField(max_length=20)),
                ('Em_Join_Date', models.DateField(max_length=20)),
                ('Em_Desin', models.TextField(max_length=20)),
                ('Em_dept', models.TimeField(max_length=20)),
                ('com_id', models.CharField(max_length=10)),
            ],
        ),
    ]
