# Generated by Django 4.2.4 on 2024-12-31 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_employee_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_info',
            old_name='Em_Id',
            new_name='comId',
        ),
        migrations.RenameField(
            model_name='employee_info',
            old_name='Em_Birth_Date',
            new_name='emBirth_Date',
        ),
        migrations.RenameField(
            model_name='employee_info',
            old_name='Em_dept',
            new_name='emDept',
        ),
        migrations.RenameField(
            model_name='employee_info',
            old_name='Em_Desin',
            new_name='emDesin',
        ),
        migrations.RenameField(
            model_name='employee_info',
            old_name='Em_Email',
            new_name='emEmail',
        ),
        migrations.RenameField(
            model_name='employee_info',
            old_name='Em_Join_Date',
            new_name='emJoin_Date',
        ),
        migrations.RenameField(
            model_name='employee_info',
            old_name='Em_Mobile',
            new_name='emMobile',
        ),
        migrations.RenameField(
            model_name='employee_info',
            old_name='Em_Name',
            new_name='emName',
        ),
        migrations.RenameField(
            model_name='employee_info',
            old_name='Em_Salary',
            new_name='emSalary',
        ),
        migrations.RenameField(
            model_name='employee_info',
            old_name='com_id',
            new_name='em_Id',
        ),
    ]
