# Generated by Django 4.2.4 on 2024-12-31 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_em_id_employee_info_comid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_info',
            old_name='comId',
            new_name='com_Id',
        ),
        migrations.RenameField(
            model_name='employee_info',
            old_name='emBirth_Date',
            new_name='em_Birth_Date',
        ),
        migrations.RenameField(
            model_name='employee_info',
            old_name='emDept',
            new_name='em_Dept',
        ),
        migrations.RenameField(
            model_name='employee_info',
            old_name='emDesin',
            new_name='em_Desin',
        ),
        migrations.RenameField(
            model_name='employee_info',
            old_name='emEmail',
            new_name='em_Email',
        ),
        migrations.RenameField(
            model_name='employee_info',
            old_name='emJoin_Date',
            new_name='em_Join_Date',
        ),
        migrations.RenameField(
            model_name='employee_info',
            old_name='emMobile',
            new_name='em_Mobile',
        ),
        migrations.RenameField(
            model_name='employee_info',
            old_name='emName',
            new_name='em_Name',
        ),
        migrations.RenameField(
            model_name='employee_info',
            old_name='emSalary',
            new_name='em_Salary',
        ),
    ]
