# Generated by Django 4.2.4 on 2024-12-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_comid_employee_info_com_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_info',
            name='em_Birth_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='em_Join_Date',
            field=models.DateField(),
        ),
    ]
