# Generated by Django 4.2.4 on 2025-01-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_employee_info_em_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_info',
            name='em_Birth_Date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='em_Join_Date',
            field=models.DateTimeField(),
        ),
    ]
