# Generated by Django 4.2.4 on 2025-01-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_employee_info_em_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_info',
            name='em_Dept',
            field=models.CharField(max_length=20),
        ),
    ]
