# Generated by Django 4.2.4 on 2025-01-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_employee_info_em_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_info',
            name='em_Desin',
            field=models.CharField(max_length=20),
        ),
    ]
