# Generated by Django 4.2.4 on 2025-01-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_employee_info_em_desin'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_id', models.CharField(max_length=10)),
                ('cname', models.CharField(max_length=40)),
            ],
        ),
    ]
