# Generated by Django 4.2.4 on 2025-01-02 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_info',
            name='com_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company'),
        ),
    ]
