# Generated by Django 4.2.4 on 2025-01-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_employee_info_com_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_info',
            name='com_Id',
            field=models.CharField(max_length=10),
        ),
    ]
