# Generated by Django 4.2.4 on 2025-01-28 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_employee_info_com_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='com_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='com_Id',
            field=models.ForeignKey(choices=[('01', 'SAF'), ('02', 'FFA'), ('03', 'SSA')], default='SAF', on_delete=django.db.models.deletion.CASCADE, to='myapp.company'),
        ),
    ]
