# Generated by Django 4.2.4 on 2025-02-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_company_com_id_alter_employee_info_com_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_info',
            name='com_Id',
            field=models.CharField(choices=[('01', 'SAF'), ('02', 'FFA'), ('03', 'SSA')], default='01', max_length=2),
        ),
    ]
