# Generated by Django 4.2.4 on 2025-09-01 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_budget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='budget',
        ),
    ]
