# Generated by Django 4.2.4 on 2025-09-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='b_id',
            field=models.CharField(max_length=20),
        ),
    ]
